version: 1.0.{build}

environment:
  secured_passwd:
    secure: 0cRRPfYLuFHGktDapSOefg==

install:
  - cinst biicode # will install biicode 2.0.1 and cmake 3.0.2
  - cmd: cmake --version
  - cmd: bii -v
  - cmd: echo yes | bii setup:cpp
  - cmd: del bii-win.exe
  - cmd: del cmake.zip

before_build:
  - cmd: bii init myproject
  - cmd: cd myproject
  - cmd: bii new diego/libcello
  # Yes, I know, sure this move can be improved
  - cmd: move ..\* blocks\diego\libcello\
  - cmd: move ..\demos blocks\diego\libcello\
  - cmd: move ..\include blocks\diego\libcello\
  - cmd: move ..\src blocks\diego\libcello\
  - cmd: move ..\editors blocks\diego\libcello\
  - cmd: move ..\tests blocks\diego\libcello\

build_script:
  - cmd: bii cpp:build

test_script:
  - cmd: bin\diego_libcello_tests_test.exe

# to run your custom scripts instead of provider deployments
deploy_script:
  - cmd: bii user diego -p %secured_passwd%
  - cmd: bii publish


